#pragma once

#define HAUTEUR_GRILLE 500
#define LARGEUR_GRILLE 500
#define RESSOURCES_EAU 100
#define RESSOURCES_TERRE 0
#define RESSOURCES_GAZON 1000
#define RATE_GAZON 100
#define RESSOURCES_FRONTIERE 0